### ISSUE TITLE
Error running search on training set 

### ISSUE THREAD

**Issue by himsR** [yorkeyao/DataCV2024#1]
Hello,

On running the command - 

 python trainingset_search_detection_vehicle.py --target 'region100' \
--select_method 'SnP' --c_num 50 \
--result_dir 'main_results/sample_data_detection_vehicle_region100/' \
--n_num 8000 \
--output_data '/data/detection_data/trainingset_search/SnP_region100_vehicle_8000_random_c_num50.json'  

I get the following error 

Propagating batch 305/307████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 304/306 [1:12:43<00:15,  7.98s/it]
Propagating batch 306/307█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 305/306 [1:12:54<00:08,  8.75s/it]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 306/306 [1:13:09<00:00, 14.35s/it]

=========== extracting feature of data pool ===========
Warning: batch size is bigger than the data size. Setting batch size to data size 0
Traceback (most recent call last):
  File "/home/himanshu/comp/code/DataCV2024-main/SnP_detection/trainingset_search_detection_vehicle.py", line 69, in <module>
    sampled_data = feat_stas.SnP_detection.training_set_search(target, data_dict, annotation_dict, databse_id, opt, result_dir, c_num, version = "vehicle")
  File "/home/himanshu/comp/code/DataCV2024-main/SnP_detection/feat_stas/SnP_detection.py", line 155, in training_set_search
    feature_infer = get_activations(opt, img_paths, model, batch_size, dims, cuda, verbose=False)
  File "/home/himanshu/comp/code/DataCV2024-main/SnP_detection/feat_stas/feat_extraction.py", line 71, in get_activations
    n_batches = len(files) // batch_size
ZeroDivisionError: integer division or modulo by zero

**Comment by CaseSplash90039** [comment]
Could you please check whether both source pool datasets and region100 have been loaded successfully？ If not, such error can happen.

**Comment by himsR** [comment]
Hi @CaseSplash90039 , thank you for pointing this out. On debugging I found out that the reason it wasn't reading the images was this :  CLASSES = ('car',) . On changing it to CLASSES = 'car' (string instead of a tuple ), it started reading images. 

On another note, where can I find the '/yaoy/kevin/random_sample_region100_vehicle_8000.json' file mentioned in the custom_tss.py file? Thanks

**Comment by yorkeyao** [comment]
Hi himsR,

random_sample_region100_vehicle_8000.json is the training set search output, and can be obtained by 

python trainingset_search_detection_vehicle.py --target 'region100' \
--select_method 'random' --c_num 50 \
--result_dir 'main_results/sample_data_detection_vehicle_region100/' \
--n_num 8000 \
--output_data '/data/detection_data/trainingset_search/random_sample_region100_vehicle_8000.json'

**Comment by himsR** [comment]
Thank you! On plugging the file and training retinanet, I get the foloowing error:


after_run:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
2024-02-23 23:11:33,294 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
2024-02-23 23:11:33,294 - mmdet - INFO - Checkpoints will be saved to /home/himanshu/comp/code/DataCV2024-main/task_model/mmdetection/work_dirs/retinanet_r50_fpn_1x_custom_tss_car by HardDiskBackend.
Traceback (most recent call last):
  File "/home/himanshu/comp/code/DataCV2024-main/task_model/mmdetection/tools/train.py", line 244, in <module>
    main()
  File "/home/himanshu/comp/code/DataCV2024-main/task_model/mmdetection/tools/train.py", line 233, in main
    train_detector(
  File "/home/himanshu/comp/code/DataCV2024-main/task_model/mmdetection/mmdet/apis/train.py", line 246, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/himanshu/anaconda3/envs/pytorch/lib/python3.10/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/himanshu/anaconda3/envs/pytorch/lib/python3.10/site-packages/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/himanshu/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 368, in __iter__
    return self._get_iterator()
  File "/home/himanshu/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 314, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/himanshu/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 965, in __init__
    self._reset(loader, first_iter=True)
  File "/home/himanshu/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 996, in _reset
    self._try_put_index()
  File "/home/himanshu/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1230, in _try_put_index
    index = self._next_index()
  File "/home/himanshu/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 521, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/himanshu/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 226, in __iter__
    for idx in self.sampler:
  File "/home/himanshu/comp/code/DataCV2024-main/task_model/mmdetection/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate

Is this because dataset_aliases does not inlcude the coco_car dataset???

dataset_aliases = {
    'voc': ['voc', 'pascal_voc', 'voc07', 'voc12'],
    'imagenet_det': ['det', 'imagenet_det', 'ilsvrc_det'],
    'imagenet_vid': ['vid', 'imagenet_vid', 'ilsvrc_vid'],
    'coco': ['coco', 'mscoco', 'ms_coco'],
    'wider_face': ['WIDERFaceDataset', 'wider_face', 'WIDERFace'],
    'cityscapes': ['cityscapes'],
    'oid_challenge': ['oid_challenge', 'openimages_challenge'],
    'oid_v6': ['oid_v6', 'openimages_v6']
}

Thanks

**Comment by himsR** [comment]
Thank you! This helped. Regarding geenrating a submission for the competetion : 

The repo says to use this: 
This will create a checkpoint in './work_dirs'. You may create a coco format submission using

python tools/test.py \
    configs_tss/retinanet/retinanet_r50_fpn_1x_custom_tss_car.py \
    work_dirs/retinanet_r50_fpn_1x_custom_tss_car/latest.pth \
    --format-only --options "jsonfile_prefix=./"

This does not have an output flag so I added an --out flag and provided a pickle output filename that generated a pickle output file. But the contents of the file are not in the same format as expected in the answer.txt. So is there something I am missing? Thanks a lot!

**Comment by yorkeyao** [comment]
After running this code 

python tools/test.py
configs_tss/retinanet/retinanet_r50_fpn_1x_custom_tss_car.py
work_dirs/retinanet_r50_fpn_1x_custom_tss_car/latest.pth
--format-only --options "jsonfile_prefix=./"

it will output ".bbox.json" at "./", this is the output we need. Please zip it and submit to the evaluation server.

**Comment by himsR** [comment]
The above command does not produce any outputs. This is because the --format-only flag does not save outouts. From the code in test.py: 

if args.out:
    print(f'\nwriting results to {args.out}')
    mmcv.dump(outputs, args.out)
kwargs = {} if args.eval_options is None else args.eval_options
if args.format_only:
    dataset.format_results(outputs, **kwargs)

So --out is the only flag that saves the output file. But the saved pickled file has rows like below:
[
        "[[7.5294391e+02 8.7379034e+02 8.5791736e+02 9.3840643e+02 4.0925238e-01]\n [7.2126794e+02 8.7267627e+02 8.2280573e+02 9.3539087e+02 3.4932575e-01]\n [7.7755737e+02 8.7905524e+02 8.3119226e+02 9.2573962e+02 3.4265298e-01]\n ]]"
    ],
which is not like the sample submission file.

Thank you

**Comment by yorkeyao** [comment]
The --format-only will also generate output. It is used to format the output results without performing an evaluation, as there were no labels provided for testA yet. Could you please double check whether there is a ".bbox.json" file at the path you run the test code ? 

In some situations, ".bbox.json" could be hidden by your operation system, as it begin with a dot.

**Comment by himsR** [comment]
Thank you, it was indeed a hidden file. I was able to zip the file and submit. The score is obtained following the steps is 1.30 mAP on the leaderboard. Is that the expected result? Thanks

**Comment by yorkeyao** [comment]
I think the random sample should get around 10 mAP.

**Comment by himsR** [comment]
Hi,

What's the metric being used on the evaluation server? Is the mAP metric used in coco ? and if yes, is it averaged over different region ids?

**Comment by CaseSplash90039** [comment]
Yes, mAP is used as the metric on the evaluation server.

**Comment by himsR** [comment]
Thank you! and is it averaged over all images or over the region ids? Thank you

**Comment by CaseSplash90039** [comment]
It is average over all images.
